name: Push to itch.io

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Environment
        run: yarn install
        
      - name: Build and Zip the Game
        run: yarn build-and-zip

      - name: Butler Push
        run: butler push dist/game.zip fanlix/deploy-test:html5 --userversion VERSION
        env: 
          BUTLER_API_KEY: ${{ secrets.BUTLER_CREDENTIALS }}
